### ISSUE TITLE
Adding demo for running on localhost

### ISSUE THREAD

**Issue by JackJey** [JackJey/trust-token-demo#8]
Currently this demo works only on glitch and depends on 3 domains below.

- trust-token-demo.glitch.me
- trust-token-issuer-demo.glitch.me
- trust-token-redeemer-demo.glitch.me

It's difficult to run locally, so adding standalone demo for localhost.

See Also: https://github.com/JackJey/trust-token-issuer-demo/issues/6

**Comment by bhavik-gujarati** [comment]
When trying to run this on localhost, getting the following error:

![Screenshot from 2022-08-16 18-47-46](https://user-images.githubusercontent.com/13343679/184889638-36150e32-6436-4209-8d23-bd235304b58d.png)

The chrome was opened using the following command:
`google-chrome --enable-features=TrustTokens --additional-trust-tokens-key-commitents='{"http://localhost:8000":{
 "TrustTokenV3VOPRF": {
  "id": 5,
  "protocol_version": "TrustTokenV3VOPRF",
  "batchsize": 3,
  "keys": {
   "1": {
    "Y": "AAAAAQSIBgXxnecmayp5Gqfwb/HnYRWkVAeSd+afE7bEETtsjz/SaMVy6R4XNTguWKiEp7TT5I4SBTufKcNkuXF1I4PrsueRReLJZIJc+iQNLNbQCK3U+VJthFJFYCqiyDtSDgg=",
    "expiry": "1683980602000000"
   }
  }
 }
}}'`

**Comment by JackJey** [comment]
Origin Trials for Trust Token have been finished. And this demo doesn't works anymore on current chrome.
